version: "3.4"
services:
  postgres:
    image: postgres:alpine
    volumes:
      - pg_actix:/var/lib/postgresql/data
    env_file:
      - .env-db
    ports:
      - "5432:5432"
volumes:
    pg_actix:
        driver: local