name: Build & deploy production actix backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - run: docker compose down || true
      - run: docker rmi advanced-backend_actix_api_test:local || true
      - run: docker rmi advanced-backend_nginx:latest || true
      - run: echo ${{ secrets.ENV }} | base64 -d > .env
      - run: echo ${{ secrets.ENV_DB }} | base64 -d > .env-db
      - run: docker compose up -d
